const styles = {
  pageContainer: {
    padding: "0",
    maxWidth: "100%",
    background: "transparent",
    height: "100%",
    fontFamily:
      "Maax, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  headerBar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
    padding: "16px 24px",
    flexShrink: 0,
    background: "#fff",
    borderBottom: "1px solid #e5e7eb",
  },
  title: {
    fontSize: 28,
    fontWeight: 700,
    color: "#222e3a",
    letterSpacing: 1,
    margin: 0,
  },
  headerBarGoogle: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    marginBottom: 24,
    padding: "0 24px",
  },
  googleTitle: {
    color: "#233037",
    fontWeight: 800,
    fontSize: 28,
    marginBottom: 18,
    letterSpacing: 0,
    fontFamily:
      "Maax, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  },
  googleSearchBar: {
    display: "flex",
    alignItems: "center",
    background: "#fff",
    borderRadius: 24,
    boxShadow: "0 2px 8px rgba(68,95,109,0.10)",
    border: "1.5px solid #e0e7ef",
    padding: "2px 16px 2px 12px",
    width: 320,
    transition: "box-shadow  0.2s, border 0.2s",
    marginBottom: 0,
  },
  googleSearchInput: {
    border: "none",
    outline: "none",
    background: "transparent",
    fontSize: 17,
    color: "#233037",
    padding: "10px 0 10px 8px",
    width: "100%",
    fontWeight: 500,
  },
  buttonBar: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    marginBottom: 18,
    padding: "0 24px",
  },
  button: {
    background: "#70C1B3",
    color: "#233037",
    border: "none",
    borderRadius: 8,
    padding: "10px 22px",
    fontSize: 16,
    fontWeight: 700,
    cursor: "pointer",
    boxShadow: "0 1px 2px rgba(0,0,0,0.04)",
    transition: "background 0.2s, box-shadow 0.2s",
    outline: "none",
    margin: 0,
  },
  buttonDisabled: {
    background: "#e9eef3",
    color: "#b0b8c1",
    cursor: "not-allowed",
  },
  tableContainer: {
    marginTop: 0,
    overflowX: "auto",
    overflowY: "auto",
    padding: "0",
    flex: 1,
    minHeight: 0,
    background: "#fff",
    scrollbarWidth: "none",
    msOverflowStyle: "none",
    WebkitScrollbar: { display: "none" },
  },
  table: {
    width: "100%",
    minWidth: 900,
    borderCollapse: "collapse",
    borderSpacing: 0,
    background: "#fff",
    overflow: "hidden",
    tableLayout: "auto",
  },
  th: {
    padding: "12px 16px",
    background: "rgb(255, 255, 255)",
    color: "rgb(55, 65, 81)",
    fontWeight: 500,
    fontSize: 12,
    border: "1px solid #d1d5db",
    textAlign: "left",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    position: "sticky",
    top: 0,
    zIndex: 5,
  },
  td: {
    padding: "12px 16px",
    color: "#374151",
    fontSize: 14,
    border: "1px solid #d1d5db",
    background: "#fff",
    verticalAlign: "middle",
    wordBreak: "break-word",
  },
  iconButton: {
    background: "none",
    border: "none",
    color: "#64748b",
    fontSize: 18,
    padding: 6,
    borderRadius: 6,
    cursor: "pointer",
    marginRight: 4,
    transition: "background 0.2s, color 0.2s",
    outline: "none",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  },
  iconButtonHover: {
    background: "#e0e7ef",
    color: "#2563eb",
  },
  deletingText: {
    marginLeft: 16,
    color: "#e57373",
    fontWeight: 500,
    fontSize: 15,
  },
  modalOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(34, 46, 58, 0.18)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2000,
  },
  modalContent: {
    background: "#fff",
    padding: 28,
    borderRadius: 14,
    minWidth: 260,
    maxWidth: 340,
    boxShadow: "0 6px 24px rgba(34,46,58,0.13)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    position: "relative",
    border: "1.5px solid #e5e7eb",
    transition: "box-shadow 0.2s",
    fontFamily:
      "Maax, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  },
  inventoryModalContent: {
    background: "#fff",
    padding: 20,
    borderRadius: 12,
    minWidth: 480,
    maxWidth: 520,
    width: "70vw",
    boxShadow: "0 6px 24px rgba(34,46,58,0.13)",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    position: "relative",
    border: "1.5px solid #e5e7eb",
    transition: "box-shadow 0.2s",
    maxHeight: "85vh",
    overflowY: "auto",
    scrollbarWidth: "none",
    msOverflowStyle: "none",
    WebkitScrollbar: { display: "none" },
    fontFamily:
      "Maax, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 700,
    color: "#2563eb",
    marginBottom: 16,
    letterSpacing: 0.5,
    textAlign: "center",
    fontFamily:
      "Maax, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  },
  inventoryModalTitle: {
    fontSize: 18,
    fontWeight: 700,
    color: "#2563eb",
    marginBottom: 14,
    letterSpacing: 0.5,
    textAlign: "center",
    width: "100%",
    fontFamily:
      "Maax, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  },
  inventoryInputGroup: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    marginBottom: 10,
    width: "100%",
    minWidth: 140,
  },
  inventoryLabel: {
    alignSelf: "flex-start",
    fontWeight: 500,
    color: "#222e3a",
    marginBottom: 3,
    fontSize: 13,
    fontFamily:
      "Maax, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  },
  inventoryInput: {
    width: "100%",
    minWidth: 0,
    fontSize: 13,
    padding: "6px 8px",
    borderRadius: 5,
    border: "1.2px solid #cbd5e1",
    background: "#f1f5f9",
    height: "30px",
    boxSizing: "border-box",
    marginBottom: 0,
    fontFamily:
      "Maax, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    outline: "none",
    transition: "border-color 0.2s, box-shadow 0.2s",
  },
  inventoryModalButton: {
    background: "#2563eb",
    color: "#fff",
    border: "none",
    borderRadius: 8,
    padding: "9px 20px",
    fontSize: 15,
    fontWeight: 500,
    cursor: "pointer",
    boxShadow: "0 1px 2px rgba(0,0,0,0.04)",
    transition: "background 0.2s, box-shadow 0.2s",
    outline: "none",
    fontFamily:
      "Maax, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  },
  inventoryModalButtonSmall: {
    background: "#2563eb",
    color: "#fff",
    border: "none",
    borderRadius: 7,
    padding: "7px 14px",
    fontSize: 14,
    fontWeight: 500,
    cursor: "pointer",
    marginLeft: 4,
    boxShadow: "0 1px 2px rgba(0,0,0,0.04)",
    transition: "background 0.2s, box-shadow 0.2s",
    outline: "none",
    fontFamily:
      "Maax, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  },
  inventoryModalButtonSecondary: {
    background: "#e0e7ef",
    color: "#2563eb",
    border: "none",
    borderRadius: 8,
    padding: "9px 20px",
    fontSize: 15,
    fontWeight: 500,
    cursor: "pointer",
    marginLeft: 4,
    boxShadow: "0 1px 2px rgba(0,0,0,0.04)",
    transition: "background 0.2s, box-shadow 0.2s",
    outline: "none",
    fontFamily:
      "Maax, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  },
  modalCheckbox: {
    accentColor: "#2563eb",
    width: 18,
    height: 18,
    marginRight: 8,
  },
  modalSection: {
    width: "100%",
    marginBottom: 14,
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
  },
  modalLabel: {
    fontWeight: 500,
    color: "#222e3a",
    marginBottom: 5,
    fontSize: 15,
    textAlign: "left",
    width: "100%",
    fontFamily:
      "Maax, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  },
  actionEditButton: {
    background: "transparent",
    border: "none",
    borderRadius: 4,
    padding: "6px",
    cursor: "pointer",
    transition: "background 0.18s",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  actionEditButtonHover: {
    background: "#dbeafe",
  },
  actionDeleteButton: {
    background: "transparent",
    border: "none",
    borderRadius: 4,
    padding: "6px",
    cursor: "pointer",
    transition: "background 0.18s",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  actionDeleteButtonHover: {
    background: "#fef2f2",
  },
  tabButton: {
    border: "none",
    padding: "8px 12px",
    fontSize: 13,
    fontWeight: 500,
    cursor: "pointer",
    borderRadius: "6px 6px 0 0",
    transition: "all 0.2s",
    display: "flex",
    alignItems: "center",
    boxShadow: "0 1px 2px rgba(0,0,0,0.05)",
    minWidth: 80,
    maxWidth: 120,
    justifyContent: "space-between",
    flexShrink: 0,
    fontFamily:
      "Maax, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  },
  addTabButton: {
    background: "#f1f5f9",
    color: "#64748b",
    border: "1px solid #e2e8f0",
    borderRadius: 6,
    width: 32,
    height: 32,
    fontSize: 16,
    fontWeight: 600,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "all 0.2s",
    boxShadow: "0 1px 2px rgba(0,0,0,0.05)",
    fontFamily:
      "Maax, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  },
};

export default styles;
